import type { Metadata } from "next";
import { Cookie, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/custom/navbar";
import Footer from "@/components/custom/footer";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const token_method = async () => {
  const cookieStore = await cookies(); // gives access to all cookies
  const token = cookieStore.get('token')?.value;
  if (token) {
    return true
  }
  return false
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await token_method()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {token ? <></> : <Navbar />}
        <main className="min-h-screen bg-gradient-to-br from-[#111a2b] to-[#203250]">

          {children}
        </main>
        <Footer />
        <Toaster position="top-left" />
      </body>
    </html>
  );
}
